trigger:
- main

pool:
  name: COMP367Pool

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    version: '8.x'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build StringExtensionsLibNet8/StringExtensionsLibNet8.csproj --configuration $(buildConfiguration)
  displayName: 'Build library'

- script: dotnet pack StringExtensionsLibNet8/StringExtensionsLibNet8.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate to feed'

- script: |
    nuget.exe push "$(Build.ArtifactStagingDirectory)\*.nupkg" ^
      -Source "https://pkgs.dev.azure.com/comp367-jeromequayson/COMP367-Lab4-Q1/_packaging/comp367-feed/nuget/v3/index.json" ^
      -ApiKey az ^
      -NonInteractive
  displayName: 'Push package to Azure Artifacts'