trigger:
- main

pool:
  name: COMP367Pool

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    version: '8.x'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet pack StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate to feed'

- task: NuGetCommand@2
  displayName: 'Push package to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'comp367-feed'